# Model development

In [2]:
import pandas as pd 

df = pd.read_csv("taxi_cleaned_training_data.csv")
df.head()

,Trip_Distance_km,Trip_Duration_Minutes,Time_of_Day,Passenger_Count,Trip_Price
0,19.35,53.82,Morning,3.0,36.2624
1,36.87,37.27,Evening,1.0,52.9032
2,25.87,22.64,Evening,3.0,15.6180
3,8.64,89.33,Afternoon,2.0,60.2028
4,43.44,61.57,Evening,3.0,101.1216

In [3]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 716 entries, 0 to 715
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       716 non-null    float64
 1   Trip_Duration_Minutes  716 non-null    float64
 2   Time_of_Day            716 non-null    object
 3   Passenger_Count        716 non-null    float64
 4   Trip_Price             716 non-null    float64
dtypes: float64(4), object(1)
memory usage: 28.1+ KB

Trip_Distance_km         0
Trip_Duration_Minutes    0
Time_of_Day              0
Passenger_Count          0
Trip_Price               0
dtype: int64

# Sckit learn steps
0. Divide into X and y
- X = what the model can know
- y = what the model get's to predict

In [5]:
X, y = df.drop(columns="Trip_Price", axis=1), df["Trip_Price"]
X.head(2)

   Trip_Distance_km  Trip_Duration_Minutes Time_of_Day  Passenger_Count
0             19.35                  53.82     Morning              3.0
1             36.87                  37.27     Evening              1.0

In [6]:
y.head(2)

0    36.2624
1    52.9032
Name: Trip_Price, dtype: float64

## Train | test split

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)

## Dummy Encoding
- Categorical features -> represent with 1 and 0
- Categorical feature: Time_of_Day

In [13]:
X_train = pd.get_dummies(X_train, drop_first=True).astype(int)
X_test = pd.get_dummies(X_test, drop_first=True).astype(int)

X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

## Model Training 
1. Linear Regression

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)

scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

scaled_X_train.shape, scaled_X_test.shape

((572, 6), (144, 6))

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error